### ISSUE TITLE
gdrive can't find my media

### ISSUE THREAD

**Issue by martinbowling** [ddurdle/GDrive-for-KODI#107]
I have my media in 

/Incoming-Media/
     - Archive-1080
     - TV
     - Archive-Kids

It seems that it never finds my tv or movies

**Comment by ddurdle** [comment]
Please indicate what steps you have done to use the plugin.

**Comment by martinbowling** [comment]
installed latest testing version, attached a cloud_db spreadsheet

clicked on my media folders and said scan media info.

No streams and no cloud_db entries seemed to be filled

**Comment by ddurdle** [comment]
Go to Video Addons -> gdrive-testing -> [enroll account], follow instructions.

Then go to  Video Addons -> gdrive-testing -> username

**Comment by martinbowling** [comment]
Yes should have noted that I did all that, the account authorized fine, I can see all the files but when I scan media info nothing happens

**Comment by ddurdle** [comment]
On your files, right click and select "save STRM".  On the video folder in Video -> Files, select scan media and select appropriate scrapper (tv, movies).

**Comment by martinbowling** [comment]
Oh ok I misunderstood, I thought if I used Scan Media Info that it would organize and build Movies STRM and TV STRM
