### ISSUE TITLE
Resume Points Not Working

### ISSUE THREAD

**Issue by qazero** [ddurdle/GDrive-for-KODI#109]
Are resume points working? I setup gdrive using the second link on the github main page for oauth read/write access. However, when streaming from strm files, resume points don't seem to be working... I don't see any spreadsheet being stored on google drive either. Any ideas?

**Comment by ddurdle** [comment]
Is this with playback from STRM?

**Comment by qazero** [comment]
Yes.

**Comment by ddurdle** [comment]
Go here and follow the "setting up" instructions -> https://github.com/ddurdle/GDrive-for-KODI/wiki/CLOUD_DB---FAQ

**Comment by fabioneves** [comment]
I'm having this problem too, it's not resuming and I've tried setting up the spreadsheet but when I start a video and stop nothing gets populated.

Also, the options in the wiki doesn't exist in the version 0.8.37. Any help?

**Comment by ddurdle** [comment]
Let me investigate this today.  It might have become broken in one of the more recent releases.

Are you playing the content from within browse within the plugin?

Last night I was using the [SEARCH] and playing back content and it was picking up resume points, but I did not validate if it was saving them

**Comment by fabioneves** [comment]
I tried with both with STRM and browsing directly to the movie folder and playing the mkv file on the addon.

Thanks!

**Comment by ddurdle** [comment]
Can you check if the setup is completed successfully?  You should see [cloud: library] and other [cloud : *] entries when you enter the account in the plugin.  If you don't see those, it is not connecting to a spreadsheet.

I tested right now with the 0.8.37 and it is saving and updating the spreadsheet when I play random videos.  If you resume a video, it should prompt you for resume from xx:xx or start from beginning.  Are you getting this?

**Comment by ddurdle** [comment]
I did notice the WIKI is out-of-date.  I've updated that setup section.  The parameters to setup were moved to the Login screen since you can have multiple accounts and each account can have it's own spreadsheet .

###In the plugin settings, go to Login.

For the second # up-and-down arrow, change it up and down until you see the account you set up show up under "username".
Change "Resume point and playback count" to "Google Drive Spreadsheet" by pressing the up-and-down arrow.
In the previous section, when you setup the spreadsheet on your account, if you used any name other then CLOUD_DB, then enter the name of the spreadsheet in the "Spreadsheet name" field. If you used the name CLOUD_DB, you may leave this blank.

**Comment by fabioneves** [comment]
Sorry to bother, but it still doesn't work for me, here's a screenshot of my addon settings (https://i.imgur.com/oHJozs3.jpg).
- I've tried specifying a new spreadsheet name, but no go. 
- I currently have a CLOUD_DB spreadsheet in my gdrive copied from the link in the wiki and no-go.
- I even tried setting up everything again, but no dice either.
- The account was setup using your website passcode method.

Any way I can debug this?

**Comment by ddurdle** [comment]
You need to change the Resume Point to Google Spreadsheet as shown below
![image](https://cloud.githubusercontent.com/assets/851508/26328711/27bcaa0a-3f12-11e7-8a46-40bc81a25797.png)

Then you'll see some new items like the following (which will indicate it is properly connected with the Google Spreadsheet):
![image](https://cloud.githubusercontent.com/assets/851508/26328785/63e5877c-3f12-11e7-8f44-2c24be610147.png)

**Comment by fabioneves** [comment]
I always thought it was Google Spreadsheet (Write...) because it writes to the file. Sorry!
What does the other option do btw?

**Comment by ddurdle** [comment]
Other option saves to meta file information stored in Google Drive and is no longer being developed.
