### ISSUE TITLE
Own OAUTH2 Authentication

### ISSUE THREAD

**Issue by tibbsbrookside** [ddurdle/GDrive-for-KODI#110]
Hi.

As per my post on the Kodi forum:
http://forum.kodi.tv/showthread.php?tid=177557&pid=2513850#pid2513850

I'm trying to use my own OAUTH2 authentication on a LibreELEC box. So far I have done the following:

1. Installed the addon.
2. Created a new OAuth 2.0 client ID / token, as per:
http://dmdsoftware.net/GoogleSetupOAUTH2...AUTH2.html
(note that I don't have a "Drive API" option, but I do have a "Google Drive API" option)
3. In the addon settings, I've chosen a LOGIN TYPE of "YOUR OWN OAUTH2" and entered the:
USERNAME
OAUTH2 CLIENT CODE
OAUTH2 CLIENT ID
OAUTH2 CLIENT SECRET
4. Open the addon and select my username. This returns:
Login information is incorrect or permission is denied
The following account was enrolled:
5. I click OK a few times and eventually get to what looks like some folders, but nothing I recognise.
6. Checked the settings.xml file and the values are definitely correct.

In the Kodi log, it shows the following entries:
18:57:51 T:140562758113024 ERROR: gdrive: HTTP Error 400: Bad Request 
18:57:54 T:140562758113024 ERROR: Previous line repeats 1 times. 
18:57:54 T:140562758113024 ERROR: gdrive: HTTP Error 403: Forbidden 
18:57:59 T:140562758113024 ERROR: gdrive: HTTP Error 400: Bad Request 
18:57:59 T:140562758113024 ERROR: gdrive: HTTP Error 403: Forbidden 
18:58:14 T:140562722449152 ERROR: gdrive: HTTP Error 400: Bad Request 
18:58:17 T:140562722449152 ERROR: Previous line repeats 1 times. 
18:58:17 T:140562722449152 ERROR: gdrive: HTTP Error 403: Forbidden

LibreELEC and addons are all updated the to the latest stable versions.

Not sure if these will be useful, or whether you already have the details, but here are a couple of links I've found regarding the Google API versions:

https://developers.google.com/apis-explorer/#s/
https://developers.google.com/drive/v3/reference/

If you need anything testing, just let me know.

Cheers.

**Comment by ddurdle** [comment]
The new enrollment method in 0.8.64 allows the user to specify their own OAUTH credentials.
