### ISSUE TITLE
FEATURE REQUEST: marking viewed in STRM

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/GDrive-for-KODI#113]
In reference to marking viewed STRM files integrated in the Kodi library as watched... these links may assist you dmd.
https://github.com/scakemyer/quasar/commit/cabdddbcdf56efc26ba6f49648435ea275c70084
https://github.com/scakemyer/plugin.video.quasar/issues/16

**Comment by horstepipe** [comment]
Would be fantastic if this would work when using Emby for Kodi, too!

**Comment by horstepipe** [comment]
https://github.com/scakemyer/plugin.video.quasar/issues/831

Sounds promising, maybe you can get in touch with him

**Comment by ddurdle** [comment]
testing of tv series watch status update is in testing 0.8.39

**Comment by SteveMalso** [comment]
@ddurdle would it be possible to integrate native Kodi resume support too?
