### ISSUE TITLE
FEATURE REQUEST: Rclone encryption/decryption compatibility

### ISSUE THREAD

**Issue by Meiden-fc** [ddurdle/GDrive-for-KODI#114]
Be able to mount an encrypted rclone folder and streaming files using gDrive addon (the only solution right now is using Plex for Kodi addon).

https://github.com/ncw/rclone

**Comment by jbuchbinder** [comment]
Seconded. I saw something on a forum a while back about implementing [rclone "crypt"](https://rclone.org/crypt/) in addition to the current encfs support; I didn't see anything the last time I looked through the source.

**Comment by docgonzo2015** [comment]
yeah. I would love it too!

**Comment by jbuchbinder** [comment]
The reference implementation used by rclone is located here:

https://github.com/ncw/rclone/tree/master/backend/crypt

_It's a relatively trivial AES cipher (although there are varying levels of filename encryption which would have to be supported, etc). I don't have a lot of experience with python's crypto modules, but it should be easy for anyone who does._

**Comment by ddurdle** [comment]
I support python crypto modules (I have a sample salt+hash encryption algorithm included with the plugin).  I use this python crypto encryption to encrypt home security surveillance to Google Drive and is playable through the encryption support in my plugin.

I will look into if it is possible to bridge rclone crypt with python crypto.
