### ISSUE TITLE
FEATURE REQUEST - Emby plugin to stream from webui

### ISSUE THREAD

**Issue by qazero** [ddurdle/GDrive-for-KODI#116]
Currently I have imported all my strm files into Emby and playback works great within Kodi. However, would it be possible to create an Emby plugin to extend playback via Emby webui? Perhaps convert plugin:// to http://?

**Comment by ddurdle** [comment]
Work has begun on this and will post when ready.  The content will be using a http address (so it will work from any Emby client).

**Comment by loeken** [comment]
any eta on when this will be finished? cant wait for it anymore :) !

**Comment by ddurdle** [comment]
this was implemented in the project https://github.com/ddurdle/Python-GoogleDrive-VideoStream
