### ISSUE TITLE
Change audio stream (language) for videos

### ISSUE THREAD

**Issue by edcaron** [ddurdle/GDrive-for-KODI#120]
I have a dual audio video on my drive and the option to change audio stream is disabled on the kodi player options. Is there an option to change the audio stream? If there is, it'll be nice to have that feature.

**Comment by ddurdle** [comment]
investigating

**Comment by horstepipe** [comment]
Can you choose between the streams when you use the "original" version?
For transcoded versions, this is a limitation by Google. Google processes only the first audio stream (marking the stream as primary or forced is not being considered). Embedded subtitles (regardless of the format) are not being processed, either.

**Comment by ddurdle** [comment]
"Original" is playing back the file as i was originally uploaded with the
uploaded video resolution and first audio stream.  I believe it might be
possible to change which audio stream to use.

Google's transcoded versions have different resolutions but they only
select the first audio track, and they don't carry over subtitles.

**Comment by edcaron** [comment]
Thank you @horstepipe and @ddurdle. The original works fine. 😃

**Comment by ddurdle** [comment]
Are you able to select different audio track with original?

**Comment by edcaron** [comment]
Yes @ddurdle. On original I can change the audio track like if it was a local file
