### ISSUE TITLE
Library integration suggestions and insight

### ISSUE THREAD

**Issue by fabioneves** [ddurdle/GDrive-for-KODI#121]
I tried the function "<Testing - manual run of change tracking...>" and it didn't work so well in terms of folder organization, I prefer it to stick with the organization I already have on gdrive.

Going to the context menu of a folder we have an option "Save STRM" which work the way I like the most, it keeps my folder and files structure, it's awesome!

Now, it would be good if we could schedule an interval of this automatically, I have 2 folders (Movies and TVShows) and I would like to keep them in my library updated. 

Also, an option to trigger kodi library update when this routine ends would be awesome, just like SALTs (kodi addon) does.

Options I would have in Library tab:
- Account to sync: 1 / 2 / 3, etc...
- Movies directory in gdrive: pick or type dir here
- TVShows directory in gdrive: pick or type dir here
- Location to store STRM: pick local dir here
- Automatic STRM creation: yes / no
- Changes verification interval: 15 minutes / 30 minutes, etc. (if above enabled)

Thanks a lot for your work and plugin, it works wonderfully!

**Comment by jamelrom** [comment]
+1 i NEED THIS

thank you for your plugin
