### ISSUE TITLE
streamURL has issues in latest stable

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/GDrive-for-KODI#152]
Playing streamURLs is causing errors in the most current version on an android TV box.

Sample url:
plugin://plugin.video.gdrive?mode=streamURL&url=https://docs.google.com/file/d/0BzkKcwwUddEiclNvY2NhVjRHeDA/preview

(started from a m3u or strm file)

In the user select menu thats popping up in addition to the "normal" user there are also *public and public users selectable, but regardless of which one you chose, the plugin just crashes.

The log at this point spits out the following:
Code:
12:05:03.752 T:18446744072303836536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'fmtlist' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.ftmc/files/.ftmc/addons/plugin.video.gdrive/default.py", line 1078, in <module>
                                                mediaURLs = service.getPublicStream(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.ftmc/files/.ftmc/addons/plugin.video.gdrive/resources/lib/gdrive_api2.py", line 1734, in getPublicStream
                                                fmtlist, re.DOTALL):
                                            UnboundLocalError: local variable 'fmtlist' referenced before assignment
                                            -->End of Python script error report<--
12:05:03.863 T:18446744072290022472   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.gdrive/?mode=streamURL&url=https://docs.google.com/file/d/0BzkKcwwUddEiclNvY2NhVjRHeDA/preview]

Is this known behavior? Videos from the main account play without any issues.

**Comment by finalmakerr** [comment]
Confirm there is a bug!

**Comment by ddurdle** [comment]
Looks like there are some files without a proper stream mapping table.  I've updated the code to work around this and still at least play the original quality stream.  It is now in testing stream

**Comment by larocca1** [comment]
I think it is still bugged for large files. The resolved url points to a google page telling that they can't scan the file for virus because is too big and  there's a link to direct download the video

**Comment by ddurdle** [comment]
deployed to stable
