### ISSUE TITLE
search containing an apostrophe

### ISSUE THREAD

**Issue by Rick7C2** [ddurdle/GDrive-for-KODI#158]
Similar issue as https://github.com/ddurdle/GDrive-for-KODI/issues/101

Only this effects search within plugin containing apostrophe

I have fixed this using code from https://github.com/ddurdle/GDrive-for-KODI/commit/3e50de3a21e6ecb3eba2e0fef2d1d185bc9f3b54

Only posting issue for reference. 

I'll be pushing the fix to the unstable branch. This is my first time pushing a commit. Hopefully I did it right.

**Comment by ddurdle** [comment]
Thank you for the contribution.  I'll test and then merge with 0.8.60

**Comment by ddurdle** [comment]
deployed to stable
