### ISSUE TITLE
How to set original as default play option?

### ISSUE THREAD

**Issue by HuJK** [ddurdle/GDrive-for-KODI#162]
Every time when I play a video, I have to select a video quality.

I found a option can set 720p as default option.

But I want original quality as default option due to other quality can't show subtitles(.mkv file).

**Comment by ddurdle** [comment]
Select "never transcode / never stream" to force original quality always, without prompt.

**Comment by PaulinHalenria** [comment]
Hi,

Where is this option ?

**Comment by ddurdle** [comment]
![screenshot at 2018-03-03 16-21-15](https://user-images.githubusercontent.com/851508/36939436-02098df0-1eff-11e8-94e4-bcb7535785d9.png)

Option is here, as shown.
