### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by PaulinHalenria** [ddurdle/GDrive-for-KODI#165]
Hello,

I'm using OpenElec on a RaspBerry 1B
I try to connect to my GDrive the same way I do with my PI3 with Recalbox and Kodi

But always an error telling me to look in the log.
Here is the concerned log : https://pastebin.com/iPtPD3Bv

Is there an issue either with the last OpenElec or with the Raspberry Pi1 ?

Best regards
Cedric

**Comment by opensourcer2** [comment]
I can confirm that this error also appear when running Kodi 17.6 on Windows 7.  So it's not because of OpenElec or RPi.  The cause is with Kodi and/or this plug-in.

**Comment by ddurdle** [comment]
Can you write the steps to reproduce the issue?  Are you enrolling an account?  How exactly are you enrolling the account?

I completed a brand new install of OSMC on a Raspberry Pi 3B with KODI 17.6 this weekend without any issues.

**Comment by ddurdle** [comment]
Also, I noticed it is plugin.video.gdrive which is really out of date (0.8.52) whereas the code base is at 0.8.64.  Please consider installing the latest version: 

https://github.com/ddurdle/ddurdle.github.io/blob/master/repository.ddurdle-testing/plugin.video.gdrive-testing/plugin.video.gdrive-testing-0.8.64.zip

**Comment by opensourcer2** [comment]
I have updated to 0.8.66 and enroll using http://machineip:8011/enroll.  It all works now.  Thanks.
