### ISSUE TITLE
localhost refuses to connect.

### ISSUE THREAD

**Issue by PaulinoRBJ** [ddurdle/GDrive-for-KODI#176]
Okay so I've had this issue this issue in 2 seperate devices: an Android 7, another Windows 8.1, both running Krypton. I think there is something within the addon that fails, of which an indication would be the " X Gdrive error. Check the log for more information" alert I get each time I open Kodi. I'm not a developer, and I fail to find anything about the failures within the log which appears be blank. Also, this error also pops up on both of my devices, so its something that might very possibly be replicable for other users.
P.S. I did succeed in adding one of my accounts to both of the devices when localhost happened to work, but when it works, I cannot say.

**Comment by PaulinoRBJ** [comment]
![e 2](https://user-images.githubusercontent.com/39960105/41034362-f2f5b8dc-69a6-11e8-8960-80f515f38724.png)
![e 1](https://user-images.githubusercontent.com/39960105/41034363-f3633858-69a6-11e8-9c91-ad0062b4dfa4.png)
These show screenshots of me trying both the localhost and the other route, both showing a "refused to connect" error. Kodi is open, and gDrive is open within it.

**Comment by ddurdle** [comment]
I'll try to reproduce the issue on a Windows 10 machine that I have access to.

**Comment by ddurdle** [comment]
On your browser it says VPN, so I suspect this is related to the traffic going through a VPN and not to the device.
