### ISSUE TITLE
Cant play original files

### ISSUE THREAD

**Issue by ALCAMJI** [ddurdle/GDrive-for-KODI#178]
Since a couple of days when I select to play a video from my gdrive if I choose one of the google`s rendered versions it plays perfect, but if i select to play the origian lfile it doesnt play it, it only returns to the file select menu.

**Comment by ddurdle** [comment]
Which device?  which version of KODI?  Are you using plex anywhere with your google drive?

**Comment by ALCAMJI** [comment]
Nvidia shield 2017 16GB model
Kodi 17.6 from play store
Plex was preinstalled on the shield, but i have never used it.

Shield is conected with cable to a 600Mb conection and it was able to play 4k 75GB mkv without problems

**Comment by ALCAMJI** [comment]
Finally fixed, turned off my router during 1 minute to fully reset it and after turn it on againg and waiting 5 minutes everything works perfect.
