### ISSUE TITLE
I can not connect my account

### ISSUE THREAD

**Issue by ElTirillas** [ddurdle/GDrive-for-KODI#181]
When entering the dmdsoftware.net page and trying to login to my account, this image appears and I can not access my google account from Kodi, this is because it happens now and not before.

![sin titulo](https://user-images.githubusercontent.com/40409622/45119050-87e67300-b15a-11e8-9c7a-d146ff303aef.png)

**Comment by ddurdle** [comment]
The latest versions of the plugin does not use dmdsoftware.net website.

You start the plugin, click [enroll account] and follow the instructions on screen.

**Comment by ElTirillas** [comment]
And when I perform the steps indicated on the screen, I put the client ID in default, I follow the steps and when I go to Kodi it gives an incorrect login error, I do not understand
