### ISSUE TITLE
Limit instances with my own OAuth2

### ISSUE THREAD

**Issue by tatoomana** [ddurdle/GDrive-for-KODI#38]
Hello ddurdle,

I need your help, if you agree, to understand how the OAuth2.
I created my own OAuth2 for testing and I created two "Client ID." 

My goal:
One "Client ID" = a single instance of Kodi (no more.)

Why?
Because I do not want users to share their access by copying their authorization code.

My question:
Is it possible?

Thank you in advance.

Best regards.

**Comment by ddurdle** [comment]
Do you mean, you want to provide someone access to view content but you don't want them to go on and share access to someone else? 

If so, what you probably really want to do is protect the refresh token.  The access authorization token only remains active for 60 mins, after that, it becomes useless.  The refresh token allows users to continue to "refresh" their access authorization token.  This token can be protected in a manner that would allow you to share access but now allow the user to know what their refresh token is, preventing them from sharing it with anyone else.

**Comment by tatoomana** [comment]
That is almost that.

I want the peoples with whom I share my Drive, use Kodi via your addon GDrive.
The "problem" is these three elements present in the file "settings.xml"

< setting id="gdrive3_client_id" value="575**************.apps.googleusercontent.com" / >
< setting id="gdrive3_client_secret" value="YM***********RN" / >
< setting id="gdrive3_code" value="4/6*****************************mwI" / >

You can copy these three elements to another Kodi and access to the Drive.
I tested two Kodi instance simultaneously (with the same "Client ID") and it works.

My goal is to prevent this.

**Comment by ddurdle** [comment]
The code should only be a one-time use and sharing it between instances
should not work.  First time you start, it activates the code for a refresh
token.  Are you sure the refresh token is not also shared?

**Comment by tatoomana** [comment]
Sorry for my late answer. My last days were very busy.

During my test, I actually copied all this block:

<setting id="gdrive3_auth_access_token" value="" />
<setting id="gdrive3_auth_refresh_token" value="" />
<setting id="gdrive3_client_id" value="" />
<setting id="gdrive3_client_secret" value="" />
<setting id="gdrive3_code" value="" />

By following your instructions, I just copied this block:

<setting id="gdrive3_client_id" value="" />
<setting id="gdrive3_client_secret" value="" />
<setting id="gdrive3_code" value="" />

And indeed you're right, access is impossible.

So, how can I protect the refresh token ?

**Comment by ddurdle** [comment]
Work began on a proxy for this: https://github.com/ddurdle/GoogleDrive-VideoStream

**Comment by horstepipe** [comment]
hey ddurdle,
I'm new to your plugin and also want to setup it with Kodi + Emby. You said

> This token can be protected in a manner that would allow you to share access but now allow the user to know what their refresh token is, preventing them from sharing it with anyone else.

So how can the token be protected? I don't want my users to setup new devices without my knowledge.

**Comment by horstepipe** [comment]
Another question. If I want to give a user access to my google drive files from two different Kodi machines, is there a way to prevent that both devices access/stream simultaniously? So I want only one active device per user at a time, but the users should be able to have multiple devices.

**Comment by ddurdle** [comment]
By access token alone, it can be used on multiple devices simultaneously.  The protection is that it expires.

The solution you would need is a PHP script hosted on a host server that would perform the streaming -- thus the user has no access or refresh token, and you can control the number of streams used.

If you want a demo, I can set one up on a host.  I think it is what would meet your needs.

**Comment by horstepipe** [comment]
I'm not sure if I completely understood how you want to accomplish that, but a demo would be nice.

**Comment by horstepipe** [comment]
> The protection is that it expires

yeah but when the refresh token is being copied too into another Kodi instance, there is no protection isn't it?

**Comment by horstepipe** [comment]
A more general question:
Is there some kind of overview where I can see how much clients are currently access my drive?

**Comment by horstepipe** [comment]
So I can sometimes check that one user ID doesn't log in with multiple devices?
