### ISSUE TITLE
Purge cache folder

### ISSUE THREAD

**Issue by tatoomana** [ddurdle/GDrive-for-KODI#46]
Hello Ddurdle,

Is it possible to purge the cache at startup Gdrive?

I found that when I update the closed captions of video (which I have already read), Gdrive only takes into consideration the old subtitles from the cache folder.

I have to manually clear the cache for load Gdrive subtitles update.

**Comment by ddurdle** [comment]
I didn't imagine SRT or CC files would change.  I can add an option to always download.

**Comment by tatoomana** [comment]
Thank you ddurdle ! :)

Indeed, in some of my videos, I found that subtitles translations are not good or there were important synchronization problem. So I update them with new SRT.

**Comment by ddurdle** [comment]
In 0.7.7

http://dmdsoftware.net/repository.ddurdle-testing/plugin.video.gdrive-testing-0.7.7.zip

**Comment by ddurdle** [comment]
Added setting in settings to ignore cache / force download

**Comment by tatoomana** [comment]
Hello,

Forced download subtitles works. But we must find a way to purge the cache automatically (when starting GDrive for example) because it continues to take consideration the old subtitles contained in the cache folder. In addition, over time, acculation the subtitles in the cache represent significant megabytes.

**Comment by ddurdle** [comment]
I don't like to purge directories because if the user accidentally selects something like their home directory (which many users do! according to the forum and their admission they have the files going to their desktop), then the purge would destroy their home directory or system.

**Comment by tatoomana** [comment]
Otherwise, is it possible, when selecting the destination folder in Gdrive, automatically create a subfolder where the cache files will be stored ?

For example, if user choose "c:\download" in setting, Gdrive will create "c:\download\mastercache".

Like this, the purge will not cause a problem.

**Comment by ddurdle** [comment]
ok, sounds like a good idea

**Comment by ddurdle** [comment]
promoted to stable
