### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by optimusdag** [ddurdle/GDrive-for-KODI#48]
Hi,
I'm using the gdrive add-on for browsing images on my google drive. Everything works just fine, it lists the files and folders, and it shows thumbnails. But when I select one image to show on the whole screen, it just shows a black screen. Slideshow option does not work either.

Thanks in advance for your work.

**Comment by ddurdle** [comment]
Have you selected a cache folder?  What kind of device is this?

**Comment by optimusdag** [comment]
It was a cache problem.
But it took me some tries to fix it because in the cache configuration option an url appeared instead of a path, and it did not allowed me to browse the file system... only the folders under the url (I think it was a repo). Finally I managed to clear the field by returned all configurations to the default values. The I could configure a file system path and the images started to show on full screen.

Thnx
