### ISSUE TITLE
Filenames with invalid characters

### ISSUE THREAD

**Issue by pmos69** [ddurdle/GDrive-for-KODI#49]
Google Photos allows filenames with invalid characters (these are filesystem dependent), like "/" (forward slash).
The addon can retrieve/view thumbnails for such files but can't display them. 

Google drive on Windows replaces those characters with "_" in order to show the files in the explorer.

**Comment by ddurdle** [comment]
I'll implement them in the same manner (_ for /)

**Comment by ddurdle** [comment]
fixed.  In 0.7.9 for testing
