### ISSUE TITLE
STRM files being generated for .sub

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/GDrive-for-KODI#55]
'm using Testing build [v0.7.10], Kodi 15.1 on Windows 10.
I've noticed an issue when importing STRM files to the Kodi library - I'm not sure that it'll be fixed within Kodi soon (if at all) so I'll raise it here:
When .sub files are present in a folder in Google Drive, .strm files will be generated for these, so you'll get (for example):
Filename.mkv.strm
Filename.sub.strm

Unfortunately Kodi displays these as another copy of the movie (and you can't really tell from the library view, which is why, although when you try and "play" a .sub.strm you get no quality options presented). 

Would you be able to provide the ability to exclude certain file extensions from STRM creation perhaps? I noticed that version 0.7.6 seemed to export a STRM for every single file present in Google Drive, including JPGs, so I supect you've done some filtering already. It also didn't automatically detect that the folder I was exporting contained movies, but 0.7.10 does, so perhaps the fact that .STRM files aren't being produced for JPGs, etc, is because it's decided it's a movie folder :)

**Comment by ddurdle** [comment]
http://forum.kodi.tv/showthread.php?tid=177557&pid=2114819#pid2114819

**Comment by ddurdle** [comment]
-- not able to reproduct

**Comment by cappa83** [comment]
I got same error on Kodi(WIndows) and OSMC(Raspberry 2). 

So what you think what's need to reproduce that?

**Comment by ddurdle** [comment]
Details about the .sub in the web browser for Google Drive.   Is it showing up as a movie file?

**Comment by ddurdle** [comment]
sub files are being detected as 'video' in Google Drive.  Excluding them explicitly now.
