### ISSUE TITLE
Metadata and artwork?

### ISSUE THREAD

**Issue by qazero** [ddurdle/GDrive-for-KODI#69]
Is it possible to load the metadata and artwork for each movie just like in plexbmc?

**Comment by ddurdle** [comment]
The plugin already looks for fanart and title art, if present in the same
directory, and will load it.

Another option is to export to STRM and import into KODI, which will match
TV and Movies and let you playback through the KODI interface TV SHOWS and
MOVIES

**Comment by qazero** [comment]
How do I export to STRM? Is there any documentation on this? Thanks.

**Comment by negroISO** [comment]
Qazero - Here's a quick [video](https://youtu.be/j1QltZZIcFQ) I put together.

**Comment by ddurdle** [comment]
Great job!
