### ISSUE TITLE
Feature request: Yatse share

### ISSUE THREAD

**Issue by MarioKFaust** [ddurdle/GDrive-for-KODI#7]
This plugin is awesome!  Thank you for your work on it.  There's only one thing more I'd like to see it do.  I'd like to be able to share a URL to a video with XBMC from my Yatse android remote.  Example URL formats:

https://docs.google.com/file/d/xxx/edit
https://docs.google.com/file/d/xxx/preview?pli=1

Currently I have to go over to a PC and copy the URL into a .strm file.  I'd prefer to just choose Share and Send to XBMC the way I can do with the YouTube plugin.  When I try that with the current plugin, I get this in my logs:

23:45:25 T:3058446336  NOTICE: COMXPlayer: Opening: https://docs.google.com/file/d/xxx/preview?pli=1  
23:45:25 T:3058446336 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED  
23:45:25 T:2193618000  NOTICE: Thread OMXPlayer start, auto delete: false  
23:45:25 T:2193618000  NOTICE: Creating InputStream  
23:45:25 T:2193618000  NOTICE: Creating Demuxer  
23:45:25 T:2185229392  NOTICE: Thread FileCache start, auto delete: false  
23:45:26 T:2193618000   ERROR: Open - error probing input format, https://docs.google.com/file/d/xxx/preview?pli=1
23:45:26 T:2193618000   ERROR: OpenDemuxStream - Error creating demuxer  
23:45:26 T:2193618000  NOTICE: COMXPlayer::OnExit()  
23:45:26 T:2193618000  NOTICE: COMXPlayer::OnExit() deleting input stream  
23:45:26 T:3058446336  NOTICE: COMXPlayer: finished waiting                                                                        

Thanks!

**Comment by andreimoraru** [comment]
Hello,

It seems it wasn't fixed yet. I truncated short URL due to privacy reasons.

Information about the system:
```
Kodi (16.1 Git:60a76d9). Platform: Linux ARM 32-bit
Release Kodi x32 build (version for Raspberry Pi)
Kodi compiled May  1 2016 by GCC 5.3.0 for Linux ARM 32-bit version 4.4.8 (263176)
Running on OpenELEC (official) - Version: 6.95.3 7.0, kernel: Linux ARM 32-bit version 4.4.8
FFmpeg version: 2.8.6
```


Below is the error when I try to "Play on Media Center" from Google Photos version 1.25.0.129362780 on Android 5.1.1

```
14:36:50 802.111694 T:1963708416  NOTICE: DVDPlayer: Opening: https://goo.gl/photos/6C5ATNJbLPN8RU
14:36:50 802.111877 T:1963708416 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:36:50 802.113098 T:1765147552  NOTICE: Creating InputStream
14:36:51 803.611023 T:1765147552  NOTICE: Creating Demuxer
14:36:51 804.047546 T:1765147552   ERROR: Open - error probing input format, https://goo.gl/photos/6C5ATNJbLPN8RU
14:36:51 804.047791 T:1765147552   ERROR: OpenDemuxStream - Error creating demuxer
14:36:51 804.047852 T:1765147552  NOTICE: CDVDPlayer::OnExit()
14:36:51 804.052063 T:1963708416  NOTICE: CDVDPlayer::CloseFile()
14:36:51 804.052124 T:1963708416  NOTICE: DVDPlayer: waiting for threads to exit
14:36:51 804.052185 T:1963708416  NOTICE: DVDPlayer: finished waiting
14:36:51 804.052246 T:1963708416  NOTICE: CDVDPlayer::CloseFile()
14:36:51 804.052246 T:1963708416  NOTICE: DVDPlayer: waiting for threads to exit
14:36:51 804.052307 T:1963708416  NOTICE: DVDPlayer: finished waiting
```


How can I help with fixing this?

When I try to open short URL from Chrome browser and look at network request within Chrome Developer Tools, I see that Google servers return a HTTP 301 response, with the location like:
ocation:https://photos.google.com/share/AF1QipPqJQiSPipprkYCwySRoM-46Wx4UM_msDXVZVhglvC56DZkrwrr3242423Ah5RoQU2NoF-ch7U7Q?key=US1kcEMtRjweqerqdGTkleedwrWYwrJWR2xPQ3hwqewrewerhYWxjU0hjaG5ydnVB

I suspect that HTTP 301 responses are not supported by Kodi or GDrive plugin?

Many thanks,
Andrei

**Comment by ddurdle** [comment]
Are you trying to open this in Yatse remote or directly in the plugin? 

Yatse only will work with drive.google.com and docs.google.com.

If you are trying using the plugin directly, it could be something more involved.

**Comment by andreimoraru** [comment]
I am trying to open this in Yatse remote.

Do you mean it won't work for URLs containing photos.google.com ?

Thanks,
Andrei

**Comment by ddurdle** [comment]
I will have to raise a request with Yatse to include these urls in their
whitelist.

I will do some testing to ensure they are working and then raise the
request with them.

**Comment by andreimoraru** [comment]
Please let me know how I can help with this testing.

Thanks,
Andrei Moraru

**Comment by ddurdle** [comment]
implemented in 2016
