### ISSUE TITLE
Error on Kodi

### ISSUE THREAD

**Issue by bohanigans** [ddurdle/GDrive-for-KODI#71]
Hello,

I am having issues logging into my google drive on Kodi. I have completed the steps as necessary to configure the log in, (I used this guide: https://www.tvaddons.ag/googledrive-kodi/), but when I get to the part after I've completed the Google Apps sign in method on dmdsoftware.net, it then gives me a message that reads "gdrive error, check log for more information."

What log do I need to check? Is there something I am missing?

Please let me know. Thank you!

**Comment by ddurdle** [comment]
You can use the enrol account option when entering plugin.  It will prompt
you with the steps to follow.

**Comment by bohanigans** [comment]
That's exactly what I did. I have actually tried both login in types (Google Apps and OAUTH2). I followed all the steps, and yet I am still getting that error message no matter what I do.

**Comment by ddurdle** [comment]
In add-on settings for the plugin, can you please enable Logging (last panel in settings).  Then invoke the plugin and encounter the error.  A reference number should be presented on the screen.  Please provide the number in this ticket.

**Comment by michaeljfarrow** [comment]
Can this one be re-opened?  I have the same error, this is my error log.

03:39:07.464 T:5668 WARNING: Previous line repeats 2 times.
03:39:07.464 T:5668  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:d04a892d-16eb-44c5-b545-8647eb7e1782" for service "urn:upnp-org:serviceId:ContentDirectory" of device "AAA-PC: aaa:" (timeout = 300)
03:39:07.464 T:16224  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:5b9111c4-ddda-47a8-8b7e-17a2fe95cc76" for service "urn:upnp-org:serviceId:ConnectionManager" of device "AAA-PC: aaa:" (timeout = 300)
03:39:31.083 T:13884   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'URLError' object has no attribute 'code'
                                            Traceback (most recent call last):
                                              File "C:\Users\aaa\AppData\Roaming\Kodi\addons\plugin.video.gdrive\default.py", line 318, in <module>
                                                service = cloudservice2(PLUGIN_URL,addon,instanceName, user_agent, settings)
                                              File "C:\Users\aaa\AppData\Roaming\Kodi\addons\plugin.video.gdrive\resources\lib\gdrive_api2.py", line 108, in __init__
                                                self.getToken(self.addon.getSetting(self.instanceName+'_code'))
                                              File "C:\Users\aaa\AppData\Roaming\Kodi\addons\plugin.video.gdrive\resources\lib\gdrive_api2.py", line 189, in getToken
                                                if e.code == 403:
                                            AttributeError: 'URLError' object has no attribute 'code'
                                            -->End of Python script error report<--
03:39:31.134 T:14056   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.gdrive/?content_type=video&mode=enroll
03:39:31.136 T:14056   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gdrive/?content_type=video&mode=enroll) failed

**Comment by ddurdle** [comment]
Which version of KODI?

**Comment by michaeljfarrow** [comment]
17 for Windows.  There were similar issues with the Python SSL on the 
Raspberry Pi build but sadly I cannot just update my libraries like on 
Linux.

Many thanks!

**Comment by ddurdle** [comment]
There should never be an SSL issue on Raspberry Pi based KODI installs since they are Linux based.

What is the beta version for that 17?  There were early day builds with broken SSL.  You should be using >= beta 5.

**Comment by michaeljfarrow** [comment]
As far as I'm aware, this is/was the final release.  I've reinstalled 
the most recent version I can find, this is a two-day old Windows 
build.  Go to run the plugin again and get the same error.  Log says:

01:00:12.318 T:5052   ERROR: Previous line repeats 9 times.
01:00:12.318 T:5052   ERROR: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
                                              - NOTE: IGNORING THIS CAN 
LEAD TO MEMORY LEAKS!
                                             Error Type: <type 
'exceptions.AttributeError'>
                                             Error Contents: 'URLError' 
object has no attribute 'code'
                                             Traceback (most recent call 
last):
                                               File 
"C:\Users\aaa\AppData\Roaming\Kodi\addons\plugin.video.gdrive\default.py", 
line 318, in <module>
                                                 service = 
cloudservice2(PLUGIN_URL,addon,instanceName, user_agent, settings)
                                               File 
"C:\Users\aaa\AppData\Roaming\Kodi\addons\plugin.video.gdrive\resources\lib\gdrive_api2.py", 
line 108, in __init__
self.getToken(self.addon.getSetting(self.instanceName+'_code'))
                                               File 
"C:\Users\aaa\AppData\Roaming\Kodi\addons\plugin.video.gdrive\resources\lib\gdrive_api2.py", 
line 189, in getToken
                                                 if e.code == 403:
                                             AttributeError: 'URLError' 
object has no attribute 'code'
                                             -->End of Python script 
error report<--
01:00:12.331 T:7000   ERROR: XFILE::CDirectory::GetDirectory - Error 
getting 
plugin://plugin.video.gdrive/?content_type=video&instance=gdrive1&mode=main
01:00:12.333 T:7000   ERROR: 
CGUIMediaWindow::GetDirectory(plugin://plugin.video.gdrive/?content_type=video&instance=gdrive1&mode=main) 
failed
