### ISSUE TITLE
error connecting to gdrive

### ISSUE THREAD

**Issue by jbogaardt** [ddurdle/GDrive-for-KODI#76]
I installed addon to Kodi through the experimental retropie add-on to emulation station.
Despite going through the login procedures on dmdsoftware.net,  I get a gdrive error 'check log for more information.

Any help would be appreciated.

Kodi Log says the following:

04:08:00 T:1633678256  NOTICE: Previous line repeats 1 times.
04:08:00 T:1633678256  NOTICE: Thread LanguageInvoker start, auto delete: false
04:08:00 T:1946648576   ERROR: Control 550 in window 10025 has been asked to focus, but it can't
04:08:01 T:1633678256  NOTICE: -->Python Interpreter Initialized<--
04:08:03 T:1789399984  NOTICE: Thread BackgroundLoader start, auto delete: false
04:08:05 T:1633678256  NOTICE: Thread JobWorker start, auto delete: true
04:08:06 T:1616901040  NOTICE: Thread LanguageInvoker start, auto delete: false
04:08:06 T:1616901040  NOTICE: -->Python Interpreter Initialized<--
04:08:24 T:1616901040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'URLError' object has no attribute 'code'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.gdrive/default.py", line 275, in <module>
                                                service = gdrive_api2.gdrive(PLUGIN_URL,addon,instanceName, user_agent, settings)
                                              File "/home/pi/.kodi/addons/plugin.video.gdrive/resources/lib/gdrive_api2.py", line 110, in __init__
                                                self.getToken(self.addon.getSetting(self.instanceName+'_code'))
                                              File "/home/pi/.kodi/addons/plugin.video.gdrive/resources/lib/gdrive_api2.py", line 163, in getToken
                                                if e.code == 403:
                                            AttributeError: 'URLError' object has no attribute 'code'
                                            -->End of Python script error report<--
04:08:24 T:1946648576   ERROR: GetDirectory - Error getting plugin://plugin.video.gdrive/?content_type&instance=gdrive1&mode=main
04:08:24 T:1946648576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gdrive/?content_type&instance=gdrive1&mode=main) failed
04:08:24 T:1616901040  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by ddurdle** [comment]
Try using the "Enroll Account" feature in the plugin.

**Comment by jbogaardt** [comment]
Hi Ddurdle,

I thought I tried that approach when trouble-shooting on my own, but went ahead and tried it again.
In Kodi I clicked [Enroll Account]
Only one option comes up 'Google Apps' so I select this.
I make up any username I want, in this case 'jbogaardt'
I pick any generic password and a pop-up says 'The following acount was enrolled jbogaardt'
Another pop-up directs me to dmdsoftware.net, and so from my(separate)  PC while the pop-up is still up I access this URL.
I click the first option - GOOGLE APPS OAUTH2 - READ-only (DEFAULT)
I pick my gmail address from the google accounts page.
I allow Kodi to access my gdrive in the 'request for permission' page
On the next page an OAUTH2 code is shown and I am prompted for credentials.
I enter the same credentials I entered into the plugin and it tells me that sign-up is complete.
Moving back to Kodi, I click 'Okay' on the original pop-up.

After all this.  Same error occurs, and log shows:

12:00:55 T:1779700656  NOTICE: Thread JobWorker start, auto delete: true
12:01:29 T:1779700656  NOTICE: Previous line repeats 1 times.
12:01:29 T:1779700656  NOTICE: Thread LanguageInvoker start, auto delete: false
12:01:30 T:1779700656  NOTICE: -->Python Interpreter Initialized<--
12:01:32 T:1633678256  NOTICE: Thread BackgroundLoader start, auto delete: false
12:01:35 T:1633678256  NOTICE: Thread LanguageInvoker start, auto delete: false
12:01:35 T:1633678256  NOTICE: -->Python Interpreter Initialized<--
12:12:11 T:1633678256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'URLError' object has no attribute 'code'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.gdrive/default.py", line 275, in <module>
                                                service = gdrive_api2.gdrive(PLUGIN_URL,addon,instanceName, user_agent, settings)
                                              File "/home/pi/.kodi/addons/plugin.video.gdrive/resources/lib/gdrive_api2.py", line 110, in __init__
                                                self.getToken(self.addon.getSetting(self.instanceName+'_code'))
                                              File "/home/pi/.kodi/addons/plugin.video.gdrive/resources/lib/gdrive_api2.py", line 163, in getToken
                                                if e.code == 403:
                                            AttributeError: 'URLError' object has no attribute 'code'
                                            -->End of Python script error report<--
12:12:11 T:1946648576   ERROR: GetDirectory - Error getting plugin://plugin.video.gdrive/?content_type=video&mode=enroll
12:12:11 T:1946648576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gdrive/?content_type=video&mode=enroll) failed
12:12:11 T:1633678256  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by ddurdle** [comment]
It sounds like your settings.xml is corrupt.  Please locate that file in userdata/addons/plugin.video.gdrive and delete the file.  Then try the Enroll Account again.

**Comment by jbogaardt** [comment]
Ddurdle,
Thanks for the very quick response.  Deleted the file and all my attempted account set-ups were deleted from Kodi.  Retried using the 'Enroll Account' approach in Kodi (As opposed to going into Configure) Sadly, it still fails with what looks like the same error.

I have almost no coding experience, so I'm pretty lost. I went into the xml file, and it doesn't look like it is corrupt (i.e. is legible and editable)

**Comment by jbogaardt** [comment]
I tried using the add-on on a fresh install of Kodi on OSMC (Open Source Media Center running Kodi) and it worked flawlessly.  So I think it is just not compatible with the Retropie instance of Kodi  (Kodi 15.2 Git:02e7013).  Any thoughts on my conclusion would be appreciated.  Thanks!

**Comment by ddurdle** [comment]
The retropi may have a SSL issue that I have seen in some Python versions.  This is what struck in my mind when you reported it was retropi and that OSMC works.   I will need to install the retropi on a free pi to validate.

OSMC ensures the python bundled doesn't have the python issue.

I did a quick search and found similar reported issue that affects many plugins (presumably any that use SSL).   Reported here -> https://retropie.org.uk/forum/topic/327/kodi-add-ons/6

Workaround is to do the following:
sudo apt-get install --reinstall ca-certificates
sudo update-ca-certificates --fresh

There is a way around this in python to ignore certificate errors.  That would cure the issue for all systems with the issue.

**Comment by jbogaardt** [comment]
Thanks DDurdle!  ran the certificate refreshes and it works great.
