### ISSUE TITLE
Feature Request - Download transcoded stream instead of source for offline viewing.

### ISSUE THREAD

**Issue by negroISO** [ddurdle/GDrive-for-KODI#77]
Is it possible to grab the transcoded video that Google streams to you in 1080p? Right now I have over 80tb of data on Google Drive, would be nice when on the go to be able to download the already beautiful 1080p mp4/stream that Google Transcodes for you. Is it possible to capture that file through the plugin and save it locally?

**Comment by ddurdle** [comment]
In -testing version, you can right click on the video and "make offline".  If you have prompt for video quality, it will prompt and download the stream version selected or if you have the 1080p transcode as your default, it will download that.

**Comment by negroISO** [comment]
Thanks!

**Comment by negroISO** [comment]
So, I installed the testing, and I saved offline and chose 1080p, but I
can't locate the file on my Kodi. I tried locating it where the STRM for
the show is found, as well as the root for media as specified in the plugin
options.

I even did an updatedb and tried to locate filename.mkv and still couldn't
find it.

Did I miss a setting?

Thanks

**Comment by ddurdle** [comment]
cache folder location.

**Comment by negroISO** [comment]
Great, I see it now, just labeled cache.mp4 instead of STRM/filename. Not
bad. Thanks, I'll grab them one at a time. Thanks for your help again!

**Comment by ddurdle** [comment]
You must have the setting enabled to cache to a single file.  Disable this for saving to unique files.
