### ISSUE TITLE
Cant create strm from folder

### ISSUE THREAD

**Issue by brenosabino** [ddurdle/GDrive-for-KODI#78]
Creating strm from individual files work but when doing from a entire folder i get this error on log 

```
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'write'
                                            Traceback (most recent call last):
                                              File "C:\Users\Breno\AppData\Roaming\Kodi\addons\plugin.video.gdrive-testing\default.py", line 220, in <module>
                                                service.buildSTRM(path + '/'+title,folderID, contentType=contentType, pDialog=pDialog, epath=encryptedPath, dpath=dencryptedPath, encfs=encfs)
                                              File "C:\Users\Breno\AppData\Roaming\Kodi\addons\plugin.video.gdrive-testing\resources\lib\cloudservice.py", line 434, in buildSTRM
                                                self.buildSTRM(path + '/'+str(item.folder.title), item.folder.id, pDialog=pDialog, spreadsheetFile=spreadsheetFile)
                                              File "C:\Users\Breno\AppData\Roaming\Kodi\addons\plugin.video.gdrive-testing\resources\lib\cloudservice.py", line 497, in buildSTRM
                                                spreadsheetFile.write(str(item.folder.id) + '\t' + str(item.folder.title) + '\t'+str(item.file.id) + '\t'+str(item.file.title) + '\t'+str(episode)+'\t\t\t\t'+str(item.file.checksum) + '\t\t' + "\n")
                                            AttributeError: 'NoneType' object has no attribute 'write'
                                            -->End of Python script error report<--
```

Also for the files that havent been transcoded yet it shows this error on log 

ERROR: InputStream: Error opening, plugin://plugin.video.gdrive-testing/?mode=video&instance=gdrive1&folder=0...
WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.gdrive-testing/?mode=video&instance=gdrive1&folder=0

I'm on version 0.7.52

**Comment by brenosabino** [comment]
just tried using the stable version 0.7.17 and it worked fine

**Comment by negroISO** [comment]
00:22:42 T:139683295385344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'write'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.video.gdrive/default.py", line 220, in <module>
                                                service.buildSTRM(path + '/'+title,folderID, contentType=contentType, pDialog=pDialog, epath=encryptedPath, dpath=dencryptedPath, encfs=encfs)
                                              File "/home/xbmc/.kodi/addons/plugin.video.gdrive/resources/lib/cloudservice.py", line 497, in buildSTRM
                                                spreadsheetFile.write(str(item.folder.id) + '\t' + str(item.folder.title) + '\t'+str(item.file.id) + '\t'+str(item.file.title) + '\t'+str(episode)+'\t\t\t\t'+str(item.file.checksum) + '\t\t' + "\n")
                                            AttributeError: 'NoneType' object has no attribute 'write'
                                            -->End of Python script error report<--

**Comment by ddurdle** [comment]
testing in 0.8.03 http://dmdsoftware.net/repository.ddurdle-testing/plugin.video.gdrive-testing/plugin.video.gdrive-testing-0.8.03.zip

**Comment by ddurdle** [comment]
pushed to stable in 0.8.05
