### ISSUE TITLE
Feature Request: Ability to use gdrive addon as a video source in kodi.

### ISSUE THREAD

**Issue by Rick7C2** [ddurdle/GDrive-for-KODI#82]
First off I would love to see this issue https://github.com/ddurdle/GDrive-for-KODI/issues/36 implemented...

And on top of that, if it is even posble. I would like to use the gdrive addon as a regular video source in kodi. As in being able to scan in videos to the library just like it was a local hard drive. Again im not sure if there is a way of doing this but doesn;t hurt to ask right?

My goal with this is to have a system that is completly on the cloud minus kodi and the addons themselves.

With the upload ability I can save the .strms to my gdrive and add the to my kodi library via regular video source pointed to my strm folder in gdrive.

Maybe even edit the advancedsettings.xml to store the thumbnails on my gdrive account aswell.

I tried adding a video source by typing in...
plugin://plugin.video.gdrive-testing/?content_type=video&path=&folder=&instance=gdrive1&mode=index

I can view the contents of the the gdrive folder, navigate, and play, but I am unable to make kodi scan in source.

Probably a modification that needs to be done to kodi itself and not a plugin but if it is something you can do I would love to see it.

Thanks for your time.

**Comment by ddurdle** [comment]
I'm not sure the "video as source" would work as it stands.  KODI barely is able to import STRM as videos and it is not able to import them as music.

I tried looking into editing the db directly, but there is no way to create new records, only modify existing.

One of the achievable steps would be to store the meta information in Google Drive and manage it using a spreadsheet.  This is what I'm actively working on.

**Comment by Rick7C2** [comment]
Yeah thats what I figured. Thanks for looking into it.

**Comment by ddurdle** [comment]
How did you want the upload implemented?

**Comment by Rick7C2** [comment]
Honestly im not sure how it would be implemented without it working they way I described above.

as in setting other addons that can download files, to download them to plugin://plugin.video.gdrive-testing/?content_type=video&path=&folder=&instance=gdrive1&mode=index which would be a link to a folder in gdrive.

Maybe add a setting that you can set a source folder and then a destination folder (GDrive Folder) that will one way sync to gdrive.

Other than that im not sure. I'll let you know if I get any ideas.

Thanks

**Comment by ddurdle** [comment]
An example, if I had a Movie.mp4 file located on my device that I would like to add to Google Drive, how best to provide this option.  I won't be able to tie into KODI directly a right-click option that says "upload to Google Drive" if you are viewing this from a normal video source folder.

Add a [upload] item in the plugin and let user navigate to file to upload?
