### ISSUE TITLE
closed captions support broken

### ISSUE THREAD

**Issue by soylentcola** [ddurdle/GDrive-for-KODI#85]
Kodi doesn't find any subtitle track(s), if the subtitles were attached to the video file using the "closed captions" support in Google Drive. ("Closed captions" is enabled in the plugin settings)

I have 3 different Kodi installations, and all of them are having this problem after updating to the latest version (0.8.0). 
It is working on the previous stable release(0.7.17).

**Comment by ddurdle** [comment]
testing 0.8.03 in http://dmdsoftware.net/repository.ddurdle-testing/plugin.video.gdrive-testing/plugin.video.gdrive-testing-0.8.03.zip

**Comment by soylentcola** [comment]
I just did a quick test (default settings), and the closed caption track sill doesn't show up in Kodi (neither using the transcoded versions, nor the original version).

I will test it on a different Kodi setup later.
Would posting a log of opening the file (0.7.17 vs. current version) help you?

**Comment by ddurdle** [comment]
I will post a DRM-free video with a CC track in a bit (have to prepare one), so that you can test to see if the CC plays back.

**Comment by soylentcola** [comment]
It's working for me now, after I set a cache folder in settings (sorry, only did a quick test on default settings -> blank entry)

Thanks a lot for your work :)

**Comment by ddurdle** [comment]
Yes, for CC, it requires a cache path because it needs to download the TTS
and convert it to SRT for KODI to load.

Did you have a working cache path set in 0.7.17, when you tested, prior?

**Comment by soylentcola** [comment]
I was testing 0.7.17 with both, default settings (blank cache folder setting), and with a working cache folder earlier. 
Whenever the cache folder was not set, it would trigger a "select a subtitle cache folder" window, when first opening a video file with closed captions.

**Comment by ddurdle** [comment]
pushed to stable in 0.8.05
