### ISSUE TITLE
STRM Creation Failure 0.8.0 

### ISSUE THREAD

**Issue by negroISO** [ddurdle/GDrive-for-KODI#86]
Fresh reload of OpenELEC/LibreELEC and now Kodi on Ubuntu Minimal. Installed base OS, installed gdrive plugin, added my AUTH account.

I can watch streams from G-Drive but when I "Save STRM" it errors out on each build. I'm not sure what's going on.

The only settings I ever change in the plugin are:

Never Transcode - Store STRM /home/xbmc/Video - Store TV - /home/xbmc/Video/Television - Store Movies - /home/xbmc/Video/Movies - Cache Store Cache Files / home/xbmc/Cache

Am I missing folder permissions or something. I also have Resume point set to "local"

00:22:42 T:139683295385344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'write'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.video.gdrive/default.py", line 220, in <module>
                                                service.buildSTRM(path + '/'+title,folderID, contentType=contentType, pDialog=pDialog, epath=encryptedPath, dpath=dencryptedPath, encfs=encfs)
                                              File "/home/xbmc/.kodi/addons/plugin.video.gdrive/resources/lib/cloudservice.py", line 497, in buildSTRM
                                                spreadsheetFile.write(str(item.folder.id) + '\t' + str(item.folder.title) + '\t'+str(item.file.id) + '\t'+str(item.file.title) + '\t'+str(episode)+'\t\t\t\t'+str(item.file.checksum) + '\t\t' + "\n")
                                            AttributeError: 'NoneType' object has no attribute 'write'
                                            -->End of Python script error report<--

**Comment by ddurdle** [comment]
testing in 0.8.03 http://dmdsoftware.net/repository.ddurdle-testing/plugin.video.gdrive-testing/plugin.video.gdrive-testing-0.8.03.zip

**Comment by negroISO** [comment]
Didn't realize it was #78 as well, sorry for the dupe. 0.8.3 seems to have fixed the strm creation. The notification at the top of XBMC seems to pick a random STRM and just shows it up there statically when saving STRM. A quick reboot of XBMC gets rid of the notification.


Thanks again for your work!

**Comment by ddurdle** [comment]
I believe the notification was probably left-over from when you had the
issue, where the plugin crashed with an error.  Notifications are closed,
but when there is a new notification, the old one appears as well, and will
cycle in and out until a restart.

**Comment by ddurdle** [comment]
I had not seen the issue either, otherwise, it would have been fixed before
pushing out 0.8.0.  Better to have duplicates then to miss.

**Comment by ddurdle** [comment]
pushed to stable in 0.8.05

**Comment by negroISO** [comment]
Great! Thanks again!
