### ISSUE TITLE
Feature Request: Emby plugin

### ISSUE THREAD

**Issue by tatoomana** [ddurdle/GDrive-for-KODI#91]
Hi Dylan,

I started a [topic](http://emby.media/community/index.php?/topic/33488-google-drive-as-source/) for the development of a plugin for a Google Drive integration in Emby Server.

I wish to know what you think about that and maybe in the hope you can do it. :)

**Comment by ddurdle** [comment]
How would it be different then the Google Drive sync included with Emby?

**Comment by tatoomana** [comment]
The google drive sync included with Emby is only a backup for video
transcoded by Emby.

**Comment by qazero** [comment]
Any update regarding this so we can stream directly from google drive using Emby's webui?

**Comment by ddurdle** [comment]
duplicate of https://github.com/ddurdle/GDrive-for-KODI/issues/116

**Comment by ddurdle** [comment]
implemented as part of Python-GoogleDrive-VideoStream
